In [2]:
import cv2
import numpy as np 
import glob
from tqdm import tqdm
import PIL.ExifTags
import PIL.Image
import matplotlib.pyplot as plt

In [3]:
chessboard_size = (6,9)

In [4]:
obj_points = [] #3D points in real world space
img_points = [] # image plane 3D points

objp = np.zeros((np.prod(chessboard_size),3),dtype=np.float32) # initialize and return array of zeros
objp[:,:2] = np.mgrid[0:chessboard_size[0], 0:chessboard_size[1]].T.reshape(-1,2)


In [6]:
#Reading Images 
calibration_paths = glob.glob('/home/mya/Desktop/checkerphotosnew/*.jpg')
for image_path in tqdm(calibration_paths):
    #Load image
    image = cv2.imread(image_path)
    print(image)
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    print("Image loaded, Analizying...")
    #find chessboard corners
    ret,corners = cv2.findChessboardCorners(gray_image, chessboard_size, cv2.CALIB_CB_FAST_CHECK )# Use Open Cv algorith to find checkerboard corners
    if ret == True:
        print("Chessboard detected!")
        print(image_path)
        #subpixel accuracy
        criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
        cv2.cornerSubPix(gray_image, corners, (5,5), (-1,-1), criteria)
        obj_points.append(objp)
        img_points.append(corners)

    else:
        print("Chessboard not detected") 
    print(ret)
    

  4%|▍         | 1/25 [00:00<00:04,  5.20it/s]

[[[116 128 138]
  [118 130 140]
  [121 133 143]
  ...
  [149 172 187]
  [152 175 190]
  [150 173 188]]

 [[117 129 139]
  [118 130 140]
  [120 132 142]
  ...
  [150 173 188]
  [152 175 190]
  [147 170 185]]

 [[123 135 145]
  [124 136 146]
  [121 133 143]
  ...
  [149 172 187]
  [150 173 188]
  [147 170 185]]

 ...

 [[160 173 187]
  [160 173 187]
  [160 173 187]
  ...
  [ 54  91 113]
  [ 53  90 112]
  [ 49  86 108]]

 [[160 173 187]
  [160 173 187]
  [160 173 187]
  ...
  [ 50  87 109]
  [ 50  87 109]
  [ 48  85 107]]

 [[161 174 188]
  [160 173 187]
  [160 173 187]
  ...
  [ 44  81 103]
  [ 45  82 104]
  [ 44  81 103]]]
Image loaded, Analizying...
Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2220.jpg
True
[[[128 147 160]
  [126 145 158]
  [122 141 154]
  ...
  [144 167 182]
  [141 164 179]
  [137 160 175]]

 [[128 147 160]
  [128 147 160]
  [128 147 160]
  ...
  [142 165 180]
  [141 164 179]
  [140 163 178]]

 [[126 145 158]
  [127 146 159]
  [129 148 161]
  ...
  [140

 12%|█▏        | 3/25 [00:00<00:04,  5.42it/s]

Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2224.jpg
True
[[[127 143 155]
  [127 143 155]
  [128 144 156]
  ...
  [141 162 170]
  [143 164 172]
  [142 163 171]]

 [[127 143 155]
  [127 143 155]
  [127 143 155]
  ...
  [141 162 170]
  [143 164 172]
  [142 163 171]]

 [[126 142 154]
  [127 143 155]
  [127 143 155]
  ...
  [140 161 169]
  [142 163 171]
  [142 163 171]]

 ...

 [[105 121 133]
  [105 121 133]
  [105 121 133]
  ...
  [156 173 182]
  [154 171 180]
  [153 170 179]]

 [[105 121 133]
  [105 121 133]
  [105 121 133]
  ...
  [154 171 180]
  [153 170 179]
  [152 169 178]]

 [[105 121 133]
  [105 121 133]
  [105 121 133]
  ...
  [153 170 179]
  [154 171 180]
  [155 172 181]]]
Image loaded, Analizying...
Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2179.jpg
True
[[[ 95 111 123]
  [101 117 129]
  [105 121 133]
  ...
  [170 210 252]
  [169 208 252]
  [169 208 252]]

 [[ 98 114 126]
  [102 118 130]
  [104 120 132]
  ...
  [170 210 252]
  [169 208 252]
  [1

 20%|██        | 5/25 [03:52<16:14, 48.75s/it]

Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2190.jpg
True
[[[110 127 140]
  [113 130 143]
  [113 130 143]
  ...
  [149 174 190]
  [150 175 191]
  [150 175 191]]

 [[110 127 140]
  [114 131 144]
  [116 133 146]
  ...
  [149 174 190]
  [150 175 191]
  [150 175 191]]

 [[111 128 141]
  [116 133 146]
  [119 136 149]
  ...
  [149 174 190]
  [149 174 190]
  [150 175 191]]

 ...

 [[121 141 158]
  [119 139 156]
  [123 143 160]
  ...
  [165 182 195]
  [165 182 195]
  [164 181 194]]

 [[134 154 171]
  [117 137 154]
  [120 140 157]
  ...
  [166 183 196]
  [165 182 195]
  [164 181 194]]

 [[132 152 169]
  [123 143 160]
  [123 143 160]
  ...
  [167 184 197]
  [165 182 195]
  [164 181 194]]]
Image loaded, Analizying...
Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2213.jpg
True
[[[109 126 135]
  [105 122 131]
  [108 125 134]
  ...
  [141 164 179]
  [143 166 181]
  [135 158 173]]

 [[110 127 136]
  [108 125 134]
  [111 128 137]
  ...
  [137 160 175]
  [142 165 180]
  [1

 28%|██▊       | 7/25 [07:14<19:54, 66.35s/it]

Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2186.jpg
True
[[[119 137 148]
  [121 139 150]
  [122 140 151]
  ...
  [142 161 174]
  [141 160 173]
  [147 166 179]]

 [[119 137 148]
  [123 141 152]
  [124 142 153]
  ...
  [144 163 176]
  [143 162 175]
  [149 168 181]]

 [[120 138 149]
  [122 140 151]
  [122 140 151]
  ...
  [145 164 177]
  [145 164 177]
  [149 168 181]]

 ...

 [[112 128 140]
  [113 129 141]
  [111 127 139]
  ...
  [165 180 189]
  [164 179 188]
  [165 180 189]]

 [[115 131 143]
  [112 128 140]
  [112 128 140]
  ...
  [166 181 190]
  [166 181 190]
  [166 181 190]]

 [[117 133 145]
  [113 129 141]
  [115 131 143]
  ...
  [168 183 192]
  [169 184 193]
  [170 185 194]]]
Image loaded, Analizying...
Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2183.jpg
True


 36%|███▌      | 9/25 [07:14<08:41, 32.59s/it]

[[[129 150 158]
  [129 150 158]
  [130 151 159]
  ...
  [148 166 177]
  [148 166 177]
  [147 165 176]]

 [[128 149 157]
  [128 149 157]
  [129 150 158]
  ...
  [148 166 177]
  [148 166 177]
  [149 167 178]]

 [[127 148 156]
  [127 148 156]
  [127 148 156]
  ...
  [147 165 176]
  [149 167 178]
  [150 168 179]]

 ...

 [[101 115 127]
  [103 117 129]
  [102 116 128]
  ...
  [155 170 179]
  [150 165 174]
  [145 160 169]]

 [[ 98 112 124]
  [104 118 130]
  [107 121 133]
  ...
  [157 172 181]
  [150 165 174]
  [145 160 169]]

 [[ 97 111 123]
  [107 121 133]
  [113 127 139]
  ...
  [157 172 181]
  [150 165 174]
  [142 157 166]]]
Image loaded, Analizying...
Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2177.jpg
True
[[[110 127 136]
  [117 134 143]
  [114 131 140]
  ...
  [145 166 174]
  [145 166 174]
  [145 166 174]]

 [[110 127 136]
  [115 132 141]
  [115 132 141]
  ...
  [145 166 174]
  [145 166 174]
  [145 166 174]]

 [[120 137 146]
  [120 137 146]
  [121 138 147]
  ...
  [144

 40%|████      | 10/25 [10:12<19:02, 76.19s/it]

Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2210.jpg
True
[[[110 128 139]
  [111 129 140]
  [111 129 140]
  ...
  [ 44  75 100]
  [ 42  73  98]
  [ 40  71  96]]

 [[110 128 139]
  [111 129 140]
  [111 129 140]
  ...
  [ 43  74  99]
  [ 42  73  98]
  [ 40  71  96]]

 [[111 129 140]
  [111 129 140]
  [111 129 140]
  ...
  [ 43  74  99]
  [ 42  73  98]
  [ 40  71  96]]

 ...

 [[125 142 155]
  [120 137 150]
  [120 137 150]
  ...
  [149 168 183]
  [147 166 181]
  [147 166 181]]

 [[118 135 148]
  [116 133 146]
  [117 134 147]
  ...
  [150 169 184]
  [146 165 180]
  [145 164 179]]

 [[119 136 149]
  [119 136 149]
  [119 136 149]
  ...
  [145 164 179]
  [144 163 178]
  [149 168 183]]]
Image loaded, Analizying...


 44%|████▍     | 11/25 [10:13<12:31, 53.65s/it]

Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2214.jpg
True
[[[106 119 127]
  [106 119 127]
  [106 119 127]
  ...
  [ 48  77 104]
  [ 46  75 102]
  [ 44  73 100]]

 [[104 117 125]
  [105 118 126]
  [106 119 127]
  ...
  [ 47  76 103]
  [ 46  75 102]
  [ 45  74 101]]

 [[103 116 124]
  [104 117 125]
  [105 118 126]
  ...
  [ 47  76 103]
  [ 46  75 102]
  [ 46  75 102]]

 ...

 [[165 181 198]
  [165 181 198]
  [165 181 198]
  ...
  [ 23  25  35]
  [ 25  27  37]
  [ 20  22  32]]

 [[165 181 198]
  [165 181 198]
  [164 180 197]
  ...
  [ 37  39  49]
  [ 37  39  49]
  [ 29  31  41]]

 [[164 180 197]
  [164 180 197]
  [164 180 197]
  ...
  [ 32  34  44]
  [ 32  34  44]
  [ 34  36  46]]]
Image loaded, Analizying...


 52%|█████▏    | 13/25 [10:14<05:16, 26.39s/it]

Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2219.jpg
True
[[[112 130 141]
  [112 130 141]
  [111 129 140]
  ...
  [151 174 189]
  [152 175 190]
  [146 169 184]]

 [[112 130 141]
  [115 133 144]
  [116 134 145]
  ...
  [158 181 196]
  [161 184 199]
  [157 180 195]]

 [[110 128 139]
  [112 130 141]
  [112 130 141]
  ...
  [155 178 193]
  [156 179 194]
  [152 175 190]]

 ...

 [[140 157 170]
  [141 158 171]
  [143 160 173]
  ...
  [162 178 190]
  [166 182 194]
  [170 186 198]]

 [[140 157 170]
  [142 159 172]
  [144 161 174]
  ...
  [162 178 190]
  [166 182 194]
  [169 185 197]]

 [[140 157 170]
  [142 159 172]
  [144 161 174]
  ...
  [164 180 192]
  [165 181 193]
  [165 181 193]]]
Image loaded, Analizying...
Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2182.jpg
True


 56%|█████▌    | 14/25 [10:14<03:23, 18.52s/it]

[[[137 155 166]
  [129 147 158]
  [128 146 157]
  ...
  [138 162 174]
  [150 174 186]
  [168 192 204]]

 [[137 155 166]
  [130 148 159]
  [129 147 158]
  ...
  [144 168 180]
  [147 171 183]
  [154 178 190]]

 [[133 151 162]
  [128 146 157]
  [128 146 157]
  ...
  [148 172 184]
  [147 171 183]
  [147 171 183]]

 ...

 [[126 142 154]
  [125 141 153]
  [124 140 152]
  ...
  [ 15  17  17]
  [ 13  15  15]
  [ 20  22  22]]

 [[125 141 153]
  [125 141 153]
  [125 141 153]
  ...
  [ 18  20  20]
  [ 16  18  18]
  [ 20  22  22]]

 [[127 143 155]
  [126 142 154]
  [125 141 153]
  ...
  [ 21  23  23]
  [ 16  18  18]
  [ 11  13  13]]]
Image loaded, Analizying...
Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2184.jpg
True
[[[148 167 180]
  [140 159 172]
  [142 161 174]
  ...
  [107 155 189]
  [107 155 189]
  [101 149 183]]

 [[147 166 179]
  [143 162 175]
  [145 164 177]
  ...
  [103 151 185]
  [106 154 188]
  [102 150 184]]

 [[151 170 183]
  [144 163 176]
  [143 162 175]
  ...
  [100

 64%|██████▍   | 16/25 [10:14<01:22,  9.18s/it]

Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2227.jpg
True
[[[119 137 148]
  [120 138 149]
  [115 133 144]
  ...
  [144 167 182]
  [145 168 183]
  [141 164 179]]

 [[117 135 146]
  [120 138 149]
  [117 135 146]
  ...
  [145 168 183]
  [146 169 184]
  [147 170 185]]

 [[115 133 144]
  [119 137 148]
  [118 136 147]
  ...
  [144 167 182]
  [141 164 179]
  [145 168 183]]

 ...

 [[114 130 142]
  [120 136 148]
  [124 140 152]
  ...
  [143 161 172]
  [143 161 172]
  [143 161 172]]

 [[118 134 146]
  [120 136 148]
  [122 138 150]
  ...
  [143 161 172]
  [143 161 172]
  [143 161 172]]

 [[122 138 150]
  [118 134 146]
  [118 134 146]
  ...
  [144 162 173]
  [144 162 173]
  [144 162 173]]]
Image loaded, Analizying...
Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2185.jpg
True
[[[118 137 150]
  [117 136 149]
  [117 136 149]
  ...
  [171 197 221]
  [171 197 221]
  [171 197 221]]

 [[116 135 148]
  [116 135 148]
  [116 135 148]
  ...
  [171 197 221]
  [171 197 221]
  [1

 72%|███████▏  | 18/25 [11:55<03:00, 25.78s/it]

Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2209.jpg
True
[[[131 148 157]
  [134 151 160]
  [133 150 159]
  ...
  [147 165 176]
  [147 165 176]
  [147 165 176]]

 [[134 151 160]
  [132 149 158]
  [132 149 158]
  ...
  [149 167 178]
  [149 167 178]
  [149 167 178]]

 [[135 152 161]
  [133 150 159]
  [134 151 160]
  ...
  [150 168 179]
  [150 168 179]
  [150 168 179]]

 ...

 [[103 118 127]
  [103 118 127]
  [103 118 127]
  ...
  [162 178 185]
  [160 176 183]
  [158 174 181]]

 [[103 118 127]
  [103 118 127]
  [103 118 127]
  ...
  [161 177 184]
  [160 176 183]
  [158 174 181]]

 [[104 119 128]
  [104 119 128]
  [104 119 128]
  ...
  [162 178 185]
  [162 178 185]
  [160 176 183]]]
Image loaded, Analizying...
Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2178.jpg
True


 76%|███████▌  | 19/25 [11:56<01:48, 18.09s/it]

[[[120 136 148]
  [124 140 152]
  [118 134 146]
  ...
  [144 167 182]
  [143 166 181]
  [143 166 181]]

 [[121 137 149]
  [124 140 152]
  [119 135 147]
  ...
  [145 168 183]
  [144 167 182]
  [145 168 183]]

 [[122 138 150]
  [123 139 151]
  [120 136 148]
  ...
  [145 168 183]
  [146 169 184]
  [146 169 184]]

 ...

 [[124 140 152]
  [125 141 153]
  [126 142 154]
  ...
  [148 164 176]
  [152 168 180]
  [155 171 183]]

 [[125 141 153]
  [126 142 154]
  [126 142 154]
  ...
  [153 169 181]
  [155 171 183]
  [155 171 183]]

 [[128 144 156]
  [125 141 153]
  [123 139 151]
  ...
  [161 177 189]
  [161 177 189]
  [155 171 183]]]
Image loaded, Analizying...
Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2189.jpg
True
[[[132 146 158]
  [126 140 152]
  [128 142 154]
  ...
  [140 162 174]
  [137 159 171]
  [140 162 174]]

 [[129 143 155]
  [126 140 152]
  [130 144 156]
  ...
  [138 160 172]
  [141 163 175]
  [139 161 173]]

 [[127 141 153]
  [127 141 153]
  [132 146 158]
  ...
  [137

 84%|████████▍ | 21/25 [11:56<00:35,  8.97s/it]

Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2217.jpg
True
[[[110 130 141]
  [110 130 141]
  [106 126 137]
  ...
  [138 157 172]
  [138 157 172]
  [138 157 172]]

 [[111 131 142]
  [109 129 140]
  [107 127 138]
  ...
  [138 157 172]
  [138 157 172]
  [138 157 172]]

 [[109 129 140]
  [109 129 140]
  [108 128 139]
  ...
  [138 157 172]
  [138 157 172]
  [138 157 172]]

 ...

 [[107 124 133]
  [107 124 133]
  [105 122 131]
  ...
  [151 169 180]
  [146 164 175]
  [145 163 174]]

 [[106 123 132]
  [107 124 133]
  [108 125 134]
  ...
  [151 169 180]
  [148 166 177]
  [148 166 177]]

 [[104 121 130]
  [109 126 135]
  [111 128 137]
  ...
  [144 162 173]
  [154 172 183]
  [164 182 193]]]
Image loaded, Analizying...
Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2222.jpg
True


 88%|████████▊ | 22/25 [11:56<00:18,  6.33s/it]

[[[112 129 138]
  [107 124 133]
  [107 124 133]
  ...
  [140 159 172]
  [140 159 172]
  [139 158 171]]

 [[109 126 135]
  [110 127 136]
  [110 127 136]
  ...
  [140 159 172]
  [140 159 172]
  [140 159 172]]

 [[107 124 133]
  [113 130 139]
  [111 128 137]
  ...
  [140 159 172]
  [140 159 172]
  [140 159 172]]

 ...

 [[123 141 158]
  [123 141 158]
  [123 141 158]
  ...
  [169 184 193]
  [168 183 192]
  [168 183 192]]

 [[123 141 158]
  [123 141 158]
  [123 141 158]
  ...
  [168 183 192]
  [168 183 192]
  [167 182 191]]

 [[122 140 157]
  [122 140 157]
  [122 140 157]
  ...
  [171 186 195]
  [170 185 194]
  [169 184 193]]]
Image loaded, Analizying...
Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2181.jpg
True
[[[ 69  87  98]
  [ 69  87  98]
  [ 70  88  99]
  ...
  [145 164 179]
  [158 177 192]
  [155 174 189]]

 [[ 69  87  98]
  [ 70  88  99]
  [ 70  88  99]
  ...
  [152 171 186]
  [162 181 196]
  [159 178 193]]

 [[ 70  88  99]
  [ 70  88  99]
  [ 70  88  99]
  ...
  [158

 96%|█████████▌| 24/25 [11:57<00:03,  3.19s/it]

Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2216.jpg
True
[[[113 125 135]
  [117 129 139]
  [118 130 140]
  ...
  [160 182 200]
  [160 182 200]
  [160 182 200]]

 [[109 121 131]
  [115 127 137]
  [119 131 141]
  ...
  [160 182 200]
  [160 182 200]
  [160 182 200]]

 [[110 122 132]
  [118 130 140]
  [123 135 145]
  ...
  [160 182 200]
  [160 182 200]
  [160 182 200]]

 ...

 [[144 160 173]
  [144 160 173]
  [144 160 173]
  ...
  [159 173 185]
  [161 175 187]
  [162 176 188]]

 [[145 161 174]
  [145 161 174]
  [144 160 173]
  ...
  [159 173 185]
  [159 173 185]
  [160 174 186]]

 [[146 162 175]
  [145 161 174]
  [145 161 174]
  ...
  [158 172 184]
  [158 172 184]
  [159 173 185]]]
Image loaded, Analizying...
Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2226.jpg
True


100%|██████████| 25/25 [11:57<00:00, 28.69s/it]

[[[132 152 163]
  [132 152 163]
  [132 152 163]
  ...
  [156 174 185]
  [157 175 186]
  [158 176 187]]

 [[131 151 162]
  [132 152 163]
  [132 152 163]
  ...
  [156 174 185]
  [157 175 186]
  [158 176 187]]

 [[131 151 162]
  [131 151 162]
  [132 152 163]
  ...
  [156 174 185]
  [157 175 186]
  [158 176 187]]

 ...

 [[ 95 111 123]
  [ 94 110 122]
  [ 94 110 122]
  ...
  [152 169 178]
  [153 170 179]
  [155 172 181]]

 [[ 95 111 123]
  [ 95 111 123]
  [ 96 112 124]
  ...
  [156 173 182]
  [155 172 181]
  [157 174 183]]

 [[ 97 113 125]
  [ 98 114 126]
  [ 98 114 126]
  ...
  [160 177 186]
  [158 175 184]
  [159 176 185]]]
Image loaded, Analizying...
Chessboard detected!
/home/mya/Desktop/checkerphotosnew/IMG_2180.jpg
True


In [9]:
ret, K, dist, rvecs, tvecs = cv2.calibrateCamera(obj_points, img_points,gray_image.shape[::-1], None, None)
#Save parameters into numpy file
np.save("/home/mya/Desktop/camparams/ret", ret)
np.save("/home/mya/Desktop/camparams/K", K)
np.save("/home/mya/Desktop/camparams/dist", dist)
np.save("/home/mya/Desktop/camparams/rvecs", rvecs)
np.save("/home/mya/Desktop/camparams/tvecs", tvecs)


In [10]:
#Calculating the total error when it comes to projecting the points. 
mean_error = 0
for i in range(len(obj_points)):
    imgpoints2, _ = cv2.projectPoints(obj_points[i], rvecs[i], tvecs[i], K, dist)
    error = cv2.norm(img_points[i], imgpoints2, cv2.NORM_L2)/len(imgpoints2)
    mean_error += error
print( "total error: {}".format(mean_error/len(obj_points)) )
mean_error = 0

for i in range(len(obj_points)):

    imgpoints2, _ = cv2.projectPoints(obj_points[i], rvecs[i], tvecs[i], K, dist)

    error = cv2.norm(img_points[i], imgpoints2, cv2.NORM_L2)/len(imgpoints2)

    mean_error += error

print( "total error: {}".format(mean_error/len(obj_points)) )
#total error: 0.5004266581872628 Could be worse, but vould also be better



total error: 0.3420011284836295
total error: 0.3420011284836295


In [11]:
#:::::::::::::::::::::::::::::::::::::::
# Stereo 3D reconstruction Disparity Map
#::::::::::::::::::::::::::::::::::::::

In [12]:
#Load camera parameters
ret = np.load("/home/mya/Desktop/camparams/ret.npy")
K = np.load("/home/mya/Desktop/camparams/K.npy")
dist = np.load("/home/mya/Desktop/camparams/dist.npy")

In [14]:
#Specify image paths
img_path_left = "/home/mya/Desktop/dual_photos/14/leftimage.jpg"
img_path_right = "/home/mya/Desktop/dual_photos/14/rightimage.jpg"

#Load pictures
img_left = cv2.imread(img_path_left)
img_right = cv2.imread(img_path_right)

#Get height and width. Note: It assumes that both pictures are the same size. They HAVE to be same size 
h,w = img_left.shape[:2]
print(h)
print(w)


4032
3024


In [15]:
def downsample_image(image, reduce_factor):
    for i in range(0,reduce_factor):
    #Check if image is color or grayscale
        if len(image.shape) > 2:
            row,col = image.shape[:2]
        else:
            row,col = image.shape

        image = cv2.pyrDown(image, dstsize= (col//2, row // 2))
    return image



In [16]:
new_camera_matrix, roi = cv2.getOptimalNewCameraMatrix(K,dist,(w,h),1,(w,h))#Undistort images
img_left_undistorted = cv2.undistort(img_left, K, dist, None, new_camera_matrix)
img_right_undistorted = cv2.undistort(img_right, K, dist, None, new_camera_matrix)#Downsample each image 3 times (because they're too big)
img_left_downsampled = downsample_image(img_left_undistorted,3)
img_right_downsampled = downsample_image(img_right_undistorted,3)


In [18]:
def nothing(x):
    pass

cv2.namedWindow('disp',cv2.WINDOW_NORMAL)
cv2.resizeWindow('disp',700,700)

cv2.createTrackbar('numDisparities','disp',1,17,nothing)
cv2.createTrackbar('blockSize','disp',5,50,nothing)
cv2.createTrackbar('preFilterType','disp',1,1,nothing)
cv2.createTrackbar('preFilterSize','disp',2,25,nothing)
cv2.createTrackbar('preFilterCap','disp',5,63,nothing)
cv2.createTrackbar('textureThreshold','disp',10,100,nothing)
cv2.createTrackbar('uniquenessRatio','disp',15,100,nothing)
cv2.createTrackbar('speckleRange','disp',0,100,nothing)
cv2.createTrackbar('speckleWindowSize','disp',3,25,nothing)
cv2.createTrackbar('disp12MaxDiff','disp',5,25,nothing)
cv2.createTrackbar('minDisparity','disp',5,25,nothing)
# Creating an object of StereoBM algorithm

In [ ]:
# Updating the parameters based on the trackbar positions
stereo = cv2.StereoBM_create()
while True:
    numDisparities = cv2.getTrackbarPos('numDisparities','disp')*16
    blockSize = cv2.getTrackbarPos('blockSize','disp')*2 + 5
    preFilterType = cv2.getTrackbarPos('preFilterType','disp')
    preFilterSize = cv2.getTrackbarPos('preFilterSize','disp')*2 + 5
    preFilterCap = cv2.getTrackbarPos('preFilterCap','disp')
    textureThreshold = cv2.getTrackbarPos('textureThreshold','disp')
    uniquenessRatio = cv2.getTrackbarPos('uniquenessRatio','disp')
    speckleRange = cv2.getTrackbarPos('speckleRange','disp')
    speckleWindowSize = cv2.getTrackbarPos('speckleWindowSize','disp')*2
    disp12MaxDiff = cv2.getTrackbarPos('disp12MaxDiff','disp')
    minDisparity = cv2.getTrackbarPos('minDisparity','disp')

    # Setting the updated parameters before computing disparity map
    stereo.setNumDisparities(numDisparities)
    stereo.setBlockSize(blockSize)
    stereo.setPreFilterType(preFilterType)
    stereo.setPreFilterSize(preFilterSize)
    stereo.setPreFilterCap(preFilterCap)
    stereo.setTextureThreshold(textureThreshold)
    stereo.setUniquenessRatio(uniquenessRatio)
    stereo.setSpeckleRange(speckleRange)
    stereo.setSpeckleWindowSize(speckleWindowSize)
    stereo.setDisp12MaxDiff(disp12MaxDiff)
    stereo.setMinDisparity(minDisparity)

    # Calculating disparity using the StereoBM algorithm
    grayLeft = cv2.cvtColor(img_left_downsampled, cv2.COLOR_BGR2GRAY)
    grayRight= cv2.cvtColor(img_right_downsampled, cv2.COLOR_BGR2GRAY)

    disparity = stereo.compute(grayLeft,grayRight)

    # NOTE: Code returns a 16bit signed single channel image,
    # CV_16S containing a disparity map scaled by 16. Hence it
    # is essential to convert it to CV_32F and scale it down 16 times. 

    # Converting to float32
    disparity = disparity.astype(np.float32)

    # Scaling down the disparity values and normalizing them
    disparity = (disparity/16.0 - minDisparity)/numDisparities

    # Displaying the disparity map
    cv2.imshow("disp",disparity)

    # Close window using esc key
    if cv2.waitKey(1) == 27:
        break